name: CI/CD Deploy Front-End with Nginx or Apache

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn chạy CI/CD khi có thay đổi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Lấy mã nguồn từ repo

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html/EXE_201_Edumatch
            git pull origin main  # Sao chép mã nguồn từ GitHub vào VPS

            # Kiểm tra quyền truy cập
            sudo chown -R www-data:www-data /var/www/html

            # Restart Nginx hoặc Apache để áp dụng thay đổi
            sudo systemctl restart nginx  # Nếu bạn dùng Nginx
            # sudo systemctl restart apache2  # Nếu bạn dùng Apache
